Repository mvp-2003/Quikz, pull requests merged in 2024-10, with the labels that each got.

#11 Add Database Connection
  src/server/db/connect.js
  src/server/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#34 Added .github Templates
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_update.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_questions.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#32 feedback model is created and api to submit and retrieve
  src/server/controllers/feedbackController.js
  src/server/index.js
  src/server/middlewares/Auth.js
  src/server/models/feedback.js
  src/server/routes/feedbackRouter.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#36 ES LINT : SETUP
  .github/ISSUE_TEMPLATE.md
  .github/workflows/lint.yml
  src/server/.prettierrc
  src/server/controllers/feedbackController.js
  src/server/controllers/userAuthController.js
  src/server/eslint.config.mjs
  src/server/index.js
  src/server/middlewares/Auth.js
  src/server/models/user.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/feedbackRouter.js
  src/server/routes/userAuthRouters.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#43 feat: Add tag model and routes
  src/server/controllers/quizController.js
  src/server/controllers/tagController.js
  src/server/index.js
  src/server/models/quiz.js
  src/server/models/tag.js
  src/server/routes/quizRouter.js
  src/server/routes/tagRouter.js
  src/server/utils/paginate.js
Labels: enhancement, hacktoberfest

#42 Added Api Routes for Badges and Achievements
  src/server/bun.lockb
  src/server/controllers/achievementContoller.js
  src/server/controllers/badgeController.js
  src/server/controllers/userAchievementController.js
  src/server/controllers/userAuthController.js
  src/server/controllers/userBadgeController.js
  src/server/documentation.md
  src/server/index.js
  src/server/models/achievement.js
  src/server/models/badge.js
  src/server/models/user.js
  src/server/routes/achievementRouter.js
  src/server/routes/badgesRouter.js
  src/server/routes/userAchievementRouter.js
  src/server/routes/userBadgesRouter.js
Labels: enhancement, hacktoberfest
